# Setup for dependabot

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the yarn registry for updates every month
    schedule:
      interval: 'monthly'
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
